---
name: Python Test & Save

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: |
        python your-script.py > output-${{ matrix.python-version }}.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact-output-${{ matrix.python-version }}
        path: output-${{ matrix.python-version }}.txt
